name: signquill-production

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - signquill-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: signquill-minio
    ports:
      - "9001:9001"  # Console
      - "9002:9000"  # API
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=signquill
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001" --address ":9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - signquill-network
    restart: unless-stopped

  mailserver:
    image: inbucket/inbucket:latest
    container_name: signquill-mailserver
    ports:
      - "9000:9000"  # Web UI
      - "2500:2500"  # SMTP
      - "1100:1100"  # POP3
    environment:
      - INBUCKET_SMTP_DISABLED=false
      - INBUCKET_POP3_DISABLED=false
      - INBUCKET_WEB_DISABLED=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/api/v1/mailbox"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - signquill-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: signquill-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - signquill-network
    restart: unless-stopped

  signquill:
    build:
      context: ..
      dockerfile: signquill/Dockerfile
    container_name: signquill-app
    depends_on:
      database:
        condition: service_healthy
      minio:
        condition: service_started
      mailserver:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - PORT=${PORT:-3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?err}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY:?err}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:?err}
      - NEXT_PRIVATE_GOOGLE_CLIENT_ID=${NEXT_PRIVATE_GOOGLE_CLIENT_ID}
      - NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=${NEXT_PRIVATE_GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL:?err}
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL:-http://localhost:$PORT}
      - NEXT_PRIVATE_DATABASE_URL=${NEXT_PRIVATE_DATABASE_URL:?err}
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=${NEXT_PRIVATE_DIRECT_DATABASE_URL:-${NEXT_PRIVATE_DATABASE_URL}}
      - NEXT_PUBLIC_UPLOAD_TRANSPORT=${NEXT_PUBLIC_UPLOAD_TRANSPORT:-database}
      - NEXT_PRIVATE_UPLOAD_ENDPOINT=${NEXT_PRIVATE_UPLOAD_ENDPOINT}
      - NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=${NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE}
      - NEXT_PRIVATE_UPLOAD_REGION=${NEXT_PRIVATE_UPLOAD_REGION}
      - NEXT_PRIVATE_UPLOAD_BUCKET=${NEXT_PRIVATE_UPLOAD_BUCKET}
      - NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
      - NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
      - NEXT_PRIVATE_SMTP_TRANSPORT=${NEXT_PRIVATE_SMTP_TRANSPORT:?err}
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_APIKEY_USER=${NEXT_PRIVATE_SMTP_APIKEY_USER}
      - NEXT_PRIVATE_SMTP_APIKEY=${NEXT_PRIVATE_SMTP_APIKEY}
      - NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
      - NEXT_PRIVATE_SMTP_FROM_NAME=${NEXT_PRIVATE_SMTP_FROM_NAME:?err}
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=${NEXT_PRIVATE_SMTP_FROM_ADDRESS:?err}
      - NEXT_PRIVATE_SMTP_SERVICE=${NEXT_PRIVATE_SMTP_SERVICE}
      - NEXT_PRIVATE_RESEND_API_KEY=${NEXT_PRIVATE_RESEND_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_API_KEY=${NEXT_PRIVATE_MAILCHANNELS_API_KEY}
      - NEXT_PRIVATE_MAILCHANNELS_ENDPOINT=${NEXT_PRIVATE_MAILCHANNELS_ENDPOINT}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN=${NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR=${NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR}
      - NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY=${NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY}
      - NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT=${NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT}
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH:-/opt/documenso/cert.p12}
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
      # SignQuill Branding Configuration
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:?err}
      - NEXT_PUBLIC_APP_SHORT_NAME=${NEXT_PUBLIC_APP_SHORT_NAME:?err}
      - NEXT_PRIVATE_SERVICE_USER_EMAIL=${NEXT_PRIVATE_SERVICE_USER_EMAIL:?err}
      - NEXT_PRIVATE_AUTH_ISSUER=${NEXT_PRIVATE_AUTH_ISSUER:?err}
      - NEXT_PRIVATE_AUTH_RP_NAME=${NEXT_PRIVATE_AUTH_RP_NAME:?err}
      - NEXT_PRIVATE_WEBHOOK_SECRET_HEADER=${NEXT_PRIVATE_WEBHOOK_SECRET_HEADER:?err}
      - NEXT_PRIVATE_SIGNING_CERTIFICATE_TEXT=${NEXT_PRIVATE_SIGNING_CERTIFICATE_TEXT:?err}
      - NEXT_PRIVATE_ANALYTICS_DOMAIN=${NEXT_PRIVATE_ANALYTICS_DOMAIN:?err}
      - NEXT_PUBLIC_COMPANY_NAME=${NEXT_PUBLIC_COMPANY_NAME:?err}
      - NEXT_PUBLIC_COMPANY_NAME_NO_COMMA=${NEXT_PUBLIC_COMPANY_NAME_NO_COMMA:?err}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - /opt/documenso/cert.p12:/opt/documenso/cert.p12
    networks:
      - signquill-network
    restart: unless-stopped
    command: ["sh", "/app/apps/remix/start.sh"]

volumes:
  database:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  signquill-network:
    driver: bridge 